on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:
    runs - on: ubuntu - latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup - python@v4
      with:
        python - version: '3.x'

    - name: Install timeout (if needed)
      run: sudo apt - y install coreutils

    - name: Random Delay
      run: |
        delay=$((RANDOM % 120))
        echo "Delaying for $delay seconds"
        timeout $delay sleep 1

    - name: Install dependencies
      run: pip install - r requirements.txt

    - name: Run
      env:
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        ACCOUNTS_AND_PASSWORDS: ${{ secrets.ACCOUNTS_AND_PASSWORDS }}
      run: python steps.py
